import { Component } from '@angular/core';
import { DoctorService, Doctor } from '../../Services/services.service';
import { Router } from '@angular/router';
import { Location } from '@angular/common';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
 
@Component({
  selector: 'app-add-doctor',
  imports: [CommonModule,FormsModule],
  standalone:true,
  templateUrl: './add-doctor.component.html',
  styleUrls: ['./add-doctor.component.css']
})
export class AddDoctorComponent {
  doctor: Doctor = {
    doctorId: 0, // This will be auto-generated by the backend
    doctorName: '',
    specialization: '',
    doctorContactNumber: '',
    doctorEmail: ''
  };
 
  constructor(private doctorService: DoctorService, private router: Router,private location: Location,) {}
 
  // Method to add a new doctor
  addDoctor(): void {
    if (this.isFormValid()) {
      this.doctorService.addDoctor(this.doctor).subscribe(
        (response: Doctor) => {
          console.log('Doctor added successfully:', response);
          alert('Doctor added successfully!');
          this.router.navigate(['/doctor-details']); // Navigate to the doctor details page after adding
        },
        (error: any) => {
          console.error('Error adding doctor:', error);
          alert('Failed to add the doctor. Please try again.');
        }
      );
    } else {
      alert('Please fill in all required fields.');
    }
  }
 
  // Validate the form
  isFormValid(): boolean {
    return (
      this.doctor.doctorName.trim() !== '' &&
      this.doctor.specialization.trim() !== '' &&
      this.doctor.doctorContactNumber.trim() !== '' &&
      this.doctor.doctorEmail.trim() !== ''
    );
  }
  
  goBack(): void {
    this.location.back();
  }

}
 